import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillYoutube,
  AiFillFacebook,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Seng Sopheng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">seng sopheng</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1nKFzygMRLJTMtUg_mWeslpuV2nsGEXWO/view?usp=share_link"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Seng Sopheng
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Web Developer
            </h3>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/sopheng-seng-0b70a2213/" target="_blank"><AiFillLinkedin /></a>
              <a href="https://www.youtube.com/channel/UCXvvViJJyjPmzkIat6qT9lA" target="_blank"><AiFillYoutube /></a>
              <a href="https://www.facebook.com/profile.php?id=100076240566121" target="_blank"><AiFillFacebook /></a>
              <a href="https://github.com/Pheng1405" target="_blank"><AiFillGithub/></a>
              
              
            </div>
            
            <div className="container-full flex justify-center">
              <div class="rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-100 md:w-100 bg-gradient-to-b sub w-4/6 my-auto">
                          <Image src={deved} layout="fill" objectFit="cover" />
              </div>
              <div class="w-100 relative  mt-20 md:h-100 md:w-100 bg-gradient-to-b sub w-4/6 my-auto">
                    <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                    I am Seng Sopheng, a Web Developer. I really like technology. I have started studying in 2020 and I also know many programming languages as well such as C, C++, Java, JavaScript, PHP, Python, Dart, etc. and frameworks such as React.JS, Node.JS, Express.JS, etc. Currently I am learning Next.JS & Laravel. I have a lot of practice in engineering and developing, I have ever tried to build websites from scratch on my own also tried to create applications with a lot of researches by myself too.
                    In my free time I like playing football, watching anime and learning new thing.
                    </p>
                </div>
              </div>

              
          </div>
        </section>
        
      </main>
    </div>
  );
}
